@url = http://localhost:8080/appmonitor/api
@username = Joel

### LOGIN (ALL USERS)
POST {{url}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "username": "Joel",
  "password": "123"
}

> {% client.global.set('jwt-token', response.body) %}

### GET AUTHENTICATED USER
GET {{url}}/auth/user
Accept: application/json
Authorization: Bearer {{jwt-token}}

### CHANGE PASSWORD
POST {{url}}/auth/{{username}}/change-password
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt-token}}

{
  "currentPassword": "123",
  "newPassword": "1234",
  "newPasswordConfirmation": "1234"
}

