@url= http://localhost:8080/appmonitor/api
@username = Jose

### LOGIN EMPLOYEE
POST {{url}}/auth/login
Content-Type: application/json
Accept: application/json

{ "username": "Jose", "password": "123"}

> {% client.global.set('jwt-token', response.body) %}

### REQUEST USER INFO
GET {{url}}/auth/user
Accept: application/json
Authorization: Bearer {{jwt-token}}

### CHANGE PASSWORD
PATCH {{url}}/auth/{{username}}/change-password
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt-token}}

{
  "currentPassword": "123",
  "newPassword": "1234",
  "newPasswordConfirmation": "1234"
}






### GET ALL CUSTOMERS (EMPLOYEE AND ADMIN)
GET {{url}}/customers/
Accept: application/json
Authorization: Bearer {{jwt-token}}







### Get Employee by Username (ADMIN AND EMPLOYEE)
GET {{url}}/employees/Jose
Authorization: Bearer {{jwt-token}}
Content-Type: application/json

### Update Employee (ADMIN AND EMPLOYEE)
PUT {{url}}/employees/Jose
Authorization: Bearer {{jwt-token}}
Content-Type: application/json

{
  "name": "Updated Employee Name",
  "email": "updated.email@example.com",
  "warehouse": "Updated Warehouse Location"
}






### GET AVAILABLE ORDERS (EMPLOYEE AND ADMIN)
GET {{url}}/orders/available
Authorization: Bearer {{jwt-token}}

### CREATE ORDER (ADMIN AND EMPLOYEE)
POST {{url}}/orders
Authorization: Bearer {{jwt-token}}
Content-Type: application/json

{
  "id": 30,
  "customerUsername": "Tiago",
  "createdDate": "2024-11-20 21:00:00",
  "volume": {
    "id": 121,
    "sentDate": "2024-11-21 21:00:00",
    "packageTypeId": 2,
    "products": [
      {
        "productId": 2,
        "quantity": 1
      },
      {
        "productId": 1,
        "quantity": 1
      }
    ],
    "sensors": [
      {
        "id": 21,
        "sensorTypeId": 1
      },
      {
        "id": 20,
        "sensorTypeId": 2
      }
    ]
  }
}

### DELIVER ORDER (ADMIN AND EMPLOYEE)
PATCH {{url}}/orders/30/deliver
Authorization: Bearer {{jwt-token}}







### GET ALL PACKAGE TYPES (ADMIN AND EMPLOYEE)
GET {{url}}/package-types/
Authorization: Bearer {{jwt-token}}

### GET MANDATORY SENSORS FOR PACKAGE TYPE (ADMIN AND EMPLOYEE)
GET {{url}}/package-types/1/mandatory-sensors
Authorization: Bearer {{jwt-token}}







### GET ALL PRODUCT TYPES (ADMIN AND EMPLOYEE)
GET {{url}}/product-types/
Authorization: Bearer {{jwt-token}}

### GET MANDATORY SENSORS FOR PRODUCT TYPE (ADMIN AND EMPLOYEE)
GET {{url}}/product-types/1/mandatory-sensors
Authorization: Bearer {{jwt-token}}






### GET All Sensor Types (EMPLOYEE AND ADMIN)
GET {{url}}/sensor-types
Authorization: Bearer {{jwt-token}}
Content-Type: application/json






### PATCH Set Volume Delivered (EMPLOYEE AND ADMIN)
PATCH {{url}}/volumes/103/deliver
Authorization: Bearer {{jwt-token}}
Content-Type: application/json

### POST Add New Volume (EMPLOYEE AND ADMIN)
POST {{url}}/volumes
Authorization: Bearer {{jwt-token}}
Content-Type: application/json

{
  "id": 108,
  "sentDate": "2021-06-01 00:00:00",
  "orderId": 28,
  "packageTypeId": 2,
  "products": [
    {
      "productId": 1,
      "quantity": 1
    },
    {
      "productId": 2,
      "quantity": 1
    }
  ],
  "sensors": [
    {
      "id": 11,
      "sensorTypeId": 1
    },
    {
      "id": 12,
      "sensorTypeId": 2
    }
  ]
}

### GET ALL AVAILABLE VOLUMES (EMPLOYEE AND ADMIN)
GET {{url}}/volumes/available
Authorization: Bearer {{jwt-token}}