@url= http://localhost:8080/appmonitor/api
@username = Ana

### LOGIN EMPLOYEE
POST {{url}}/auth/login
Content-Type: application/json
Accept: application/json

{ "username": "Ana", "password": "123"}

> {% client.global.set('jwt-token', response.body) %}

### REQUEST USER INFO
GET {{url}}/auth/user
Accept: application/json
Authorization: Bearer {{jwt-token}}

### CHANGE PASSWORD
PATCH {{url}}/auth/{{username}}/change-password
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{jwt-token}}

{
  "currentPassword": "123",
  "newPassword": "1234",
  "newPasswordConfirmation": "1234"
}





### GET CUSTOMER'S ORDERS (MANAGER AND ADMIN)
GET {{url}}/customers/Joel/orders
Accept: application/json
Authorization: Bearer {{jwt-token}}






### Get Manager by Username (ADMIN AND MANAGER)
GET {{url}}/managers/Ana
Authorization: Bearer {{jwt-token}}

### Update Manager (ADMIN AND MANAGER)
PUT {{url}}/managers/Ana
Authorization: Bearer {{jwt-token}}
Content-Type: application/json

{
  "name": "Updated Manager Name",
  "email": "updated.manager@example.com",
  "office": "Updated Office"
}






### GET ALL ORDERS (CUSTOMER, MANAGER AND ADMIN)
GET {{url}}/orders
Authorization: Bearer {{jwt-token}}

### GET ORDER BY ID (CUSTOMER, MANAGER AND ADMIN)
GET {{url}}/orders/28
Authorization: Bearer {{jwt-token}}

### GET VOLUMES FOR ORDER (CUSTOMER, MANAGER AND ADMIN)
GET {{url}}/orders/28/volumes
Authorization: Bearer {{jwt-token}}





### GET Sensor by Id (MANAGER, CUSTOMER AND ADMIN)
GET {{url}}/sensors/3
Authorization: Bearer {{jwt-token}}





### GET All Volumes (CUSTOMER AND MANAGER AND ADMIN)
GET {{url}}/volumes
Authorization: Bearer {{jwt-token}}
Content-Type: application/json

### GET Volume by ID (CUSTOMER AND MANAGER AND ADMIN)
GET {{url}}/volumes/103
Authorization: Bearer {{jwt-token}}
Content-Type: application/json

### GET Sensors of Volume (CUSTOMER AND MANAGER AND ADMIN)
GET {{url}}/volumes/103/sensors
Authorization: Bearer {{jwt-token}}
Content-Type: application/json

### GET Products of Volume (CUSTOMER AND MANAGER AND ADMIN)
GET {{url}}/volumes/103/products
Authorization: Bearer {{jwt-token}}
Content-Type: application/json