############ EMPLOYEE RESPONSABILITIES

### GET ALL CUSTOMERS
GET http://localhost:8080/appmonitor/api/customers
Accept: application/json

### SET A DELIVER VOLUME
PATCH http://localhost:8080/appmonitor/api/volumes/1/delivered
Accept: application/json

### SET A DELIVER ORDER
PATCH http://localhost:8080/appmonitor/api/orders/1/delivered
Accept: application/json

### GET A SINGLE CUSTOMER
GET http://localhost:8080/appmonitor/api/customers/Joel
Accept: application/json

###GET ORDERS OF A CLIENT
GET http://localhost:8080/appmonitor/api/customers/Tiago/orders
Accept: application/json

###GET SENSORS OF VOLUME
GET http://localhost:8080/appmonitor/api/volumes/1/sensors
Accept: application/json

###GET PRODUCTS OF VOLUME
GET http://localhost:8080/appmonitor/api/volumes/1/products
Accept: application/json

### GET ALL PRODUCTS-TYPES
GET http://localhost:8080/appmonitor/api/product-types
Accept: application/json

### GET A SINGLE PRODUCT-TYPE
GET http://localhost:8080/appmonitor/api/product-types/1
Accept: application/json

### GET ALL PACKAGE-TYPES
GET http://localhost:8080/appmonitor/api/package-types
Accept: application/json

### GET A SINGLE PACKAGE-TYPE
GET http://localhost:8080/appmonitor/api/package-types/1
Accept: application/json

### GET ALL ORDERS
GET http://localhost:8080/appmonitor/api/orders/
Accept: application/json

### GET ALL AVAILABLE ORDERS
GET http://localhost:8080/appmonitor/api/orders/available
Accept: application/json

### PATCH DELIVERED VOLUME
PATCH http://localhost:8080/appmonitor/api/volumes/1/delivered
Content-Type: application/json


### GET SENSOR HISTORY
GET http://localhost:8080/appmonitor/api/sensors/1
Accept: application/json




### GET SINGLE ORDERS
GET http://localhost:8080/appmonitor/api/orders/1
Accept: application/json

### GET SINGLE VOLUME
GET http://localhost:8080/appmonitor/api/volumes/1
Accept: application/json



### GET VOLUMES OF ORDER
GET http://localhost:8080/appmonitor/api/orders/1/volumes
Accept: application/json

### GET ALL SENSOR-TYPES
GET http://localhost:8080/appmonitor/api/sensor-types
Accept: application/json

### GET A SINGLE SENSOR-TYPE
GET http://localhost:8080/appmonitor/api/sensor-types/1
Accept: application/json

### GET MANDATORY SENSORS OF A PRODUCT-TYPE
GET http://localhost:8080/appmonitor/api/product-types/1/mandatory-sensors

#### GET MANDATORY SENSORS OF A PACKAGE-TYPE
GET http://localhost:8080/appmonitor/api/package-types/1/mandatory-sensors

### POST A NEW ORDER
POST http://localhost:8080/appmonitor/api/orders
Content-Type: application/json

{
  "id": 28,
  "customerUsername": "Tiago",
  "createdDate": "2024-11-20T21:00:00",
  "volume": {
    "id": 103,
    "sentDate": "2024-11-21T21:00:00",
    "packageTypeId": 2,
    "products": [
      {
        "productId": 2,
        "quantity": 1
      },
      {
        "productId": 2,
        "quantity": 3
      }
    ],
    "sensors": [
      {
        "id": 3,
        "sensorTypeId": 1
      },
      {
        "id": 4,
        "sensorTypeId": 2
      }
    ]
  }
}


### POST A NEW VOLUME
POST http://localhost:8080/appmonitor/api/volumes
Content-Type: application/json

{
  "id": 105,

  "sentDate": "2021-06-01T00:00:00",
  "orderId": 27,
  "packageTypeId": 1,
  "products": [
    {
      "productId": 1,
      "quatity": 1
    },
    {
      "productId": 2,
      "quatity": 3
    }
  ],
  "sensors": [
    {
      "id": 1,
      "sensorTypeId": 1
    },
    {
      "id": 2,
      "sensorTypeId": 2
    }
  ]
}

### GET ALL ORDERS
GET http://localhost:8080/appmonitor/api/orders
Accept: application/json

### GET A SINGLE ORDER
GET http://localhost:8080/appmonitor/api/orders/27
Accept: application/json

### GET ALL VOLUMES
GET http://localhost:8080/appmonitor/api/volumes
Accept: application/json

### GET A SINGLE VOLUME
GET http://localhost:8080/appmonitor/api/volumes/1
Accept: application/json

### DELIVER A VOLUME
PATCH http://localhost:8080/appmonitor/api/volumes/1/delivered


### GET ALL sensors
GET http://localhost:8080/appmonitor/api/sensors/1/
Accept: application/json



############ LOGIN RESPONSABILITIES


### REQUEST JWT TOKEN
POST http://localhost:8080/appmonitor/api/auth/login
Content-Type: application/json
Accept: application/json

{ "username": "Joel", "password": "123"}

> {% client.global.set('jwt-token', response.body) %}

### GET ALL CUSTOMERS
GET http://localhost:8080/appmonitor/api/customers/Joel
Accept: application/json
Authorization: Bearer {{jwt-token}}