@url= http://localhost:8080/appmonitor/api

############ LOGIN RESPONSABILITIES

### REQUEST JWT TOKEN OF CUSTOMER (Joel ou Tiago)
POST {{url}}/auth/login
Content-Type: application/json
Accept: application/json

{ "username": "Joel", "password": "123"}

> {% client.global.set('jwt-token', response.body) %}


### REQUEST JWT TOKEN OF EMPLOYEE
POST {{url}}/auth/login
Content-Type: application/json
Accept: application/json

{ "username": "Jose", "password": "123"}

> {% client.global.set('jwt-token', response.body) %}


### REQUEST JWT TOKEN OF MANAGER
POST {{url}}/auth/login
Content-Type: application/json
Accept: application/json

{ "username": "Ana", "password": "123"}

> {% client.global.set('jwt-token', response.body) %}





############ CUSTOMER SERVICE

### GET ALL CUSTOMERS (EMPLOYEE)
GET {{url}}/customers
Accept: application/json
Authorization: Bearer {{jwt-token}}


### GET A SINGLE CUSTOMER (CUSTOMER)
GET {{url}}/customers/Joel
Accept: application/json
Authorization: Bearer {{jwt-token}}

### GET ORDERS OF A CUSTOMER (CUSTOMER)
GET {{url}}/customers/Joel/orders
Accept: application/json
Authorization: Bearer {{jwt-token}}





############ ORDER SERVICE

### GET ALL ORDERS (CUSTOMER, MANAGER)
GET {{url}}/orders
Accept: application/json
Authorization: Bearer {{jwt-token}}

### GET AVAILABLE ORDERS (EMPLOYEE)
GET {{url}}/orders/available
Accept: application/json
Authorization: Bearer {{jwt-token}}

### POST A NEW ORDER (EMPLOYEE)
POST http://localhost:8080/appmonitor/api/orders
Content-Type: application/json
Authorization: Bearer {{jwt-token}}

{
  "id": 29,
  "customerUsername": "Tiago",
  "createdDate": "2024-11-20T21:00:00",
  "volume": {
    "id": 120,
    "sentDate": "2024-11-21T21:00:00",
    "packageTypeId": 2,
    "products": [
      {
        "productId": 2,
        "quantity": 1
      },
      {
        "productId": 2,
        "quantity": 3
      }
    ],
    "sensors": [
      {
        "id": 10,
        "sensorTypeId": 1
      },
      {
        "id": 9,
        "sensorTypeId": 2
      }
    ]
  }
}

### GET A SINGLE ORDER (CUSTOMER, MANAGER)
GET {{url}}/orders/28
Accept: application/json
Authorization: Bearer {{jwt-token}}

### GET VOLUMES OF ORDER (CUSTOMER, MANAGER)
GET {{url}}/orders/28/volumes
Accept: application/json
Authorization: Bearer {{jwt-token}}

### DELIVER ORDER (EMPLOYEE)
PATCH {{url}}/orders/28/deliver
Accept: application/json
Authorization: Bearer {{jwt-token}}





############ VOLUME SERVICE

### GET A SPECIFIC VOLUME (CUSTOMER, MANAGER)
GET {{url}}/volumes/103
Accept: application/json
Authorization: Bearer {{jwt-token}}

### GET ALL SENSORS OF A VOLUME (CUSTOMER, MANAGER)
GET {{url}}/volumes/103/sensors
Accept: application/json
Authorization: Bearer {{jwt-token}}

### GET ALL PRODUCTS OF A VOLUME (CUSTOMER, MANAGER)
GET {{url}}/volumes/103/products
Accept: application/json
Authorization: Bearer {{jwt-token}}

### DELIVER VOLUME (EMPLOYEE)
PATCH {{url}}/volumes/103/deliver
Accept: application/json
Authorization: Bearer {{jwt-token}}

### POST A NEW VOLUME (EMPLOYEE)
POST http://localhost:8080/appmonitor/api/volumes
Content-Type: application/json
Authorization: Bearer {{jwt-token}}

{
  "id": 108,
  "sentDate": "2021-06-01T00:00:00",
  "orderId": 28,
  "packageTypeId": 1,
  "products": [
    {
      "productId": 1,
      "quantity": 1
    },
    {
      "productId": 2,
      "quantity": 3
    }
  ],
  "sensors": [
    {
      "id": 11,
      "sensorTypeId": 1
    },
    {
      "id": 12,
      "sensorTypeId": 2
    }
  ]
}





############ SENSOR SERVICE

### GET ALL SENSORS (EMPLOYEE)
GET {{url}}/sensors
Accept: application/json
Authorization: Bearer {{jwt-token}}

### GET A SINGLE SENSOR (MANAGER, CUSTOMER)
GET {{url}}/sensors/1
Accept: application/json
Authorization: Bearer {{jwt-token}}

### POST A NEW VALUE
POST {{url}}/sensors/1/add-value
Content-Type: application/json
Accept: application/json

{
  "value": 10
}





############ PRODUCT-TYPE SERVICE

### GET ALL PRODUCT-TYPES (EMPLOYEE)
GET {{url}}/product-types
Accept: application/json
Authorization: Bearer {{jwt-token}}

### GET ALL MANDATORY SENSORS OF A PRODUCT-TYPE (EMPLOYEE)
GET {{url}}/product-types/1/mandatory-sensors
Accept: application/json
Authorization: Bearer {{jwt-token}}





############ PACKAGE-TYPE SERVICE

### GET ALL PACKAGE-TYPES (EMPLOYEE)
GET {{url}}/package-types
Accept: application/json
Authorization: Bearer {{jwt-token}}

### GET ALL MANDATORY SENSORS OF A PACKAGE-TYPE (EMPLOYEE)
GET {{url}}/package-types/1/mandatory-sensors
Accept: application/json
Authorization: Bearer {{jwt-token}}





############ SENSOR-TYPE SERVICE

### GET ALL SENSOR-TYPES (EMPLOYEE)
GET {{url}}/sensor-types
Accept: application/json
Authorization: Bearer {{jwt-token}}